#!/usr/bin/env python3
"""Render the immutable H2-to-H3 R3 transition migration from docs/instrument.json."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "docs" / "instrument.json"
OUTPUT = ROOT / "supabase" / "migrations" / "202609080007_activate_r3_h3.sql"
H2_HASH = "192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad"


def canonical_json(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sql(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    if OUTPUT.exists():
        raise SystemExit(f"refusing to overwrite existing migration: {OUTPUT}")
    instrument = json.loads(INPUT.read_text(encoding="utf-8"))
    declared = instrument.pop("instrument_sha256", "")
    calculated = hashlib.sha256(canonical_json(instrument)).hexdigest()
    if declared != calculated:
        raise SystemExit("instrument hash mismatch")
    if instrument.get("hosted_version") != "v260908-r3-preview-1":
        raise SystemExit("unexpected R3 hosted version")
    if instrument.get("dataset_role") != "r3_content_response_pilot":
        raise SystemExit("unexpected R3 dataset role")
    assignments = instrument.get("assignments")
    if not isinstance(assignments, dict) or sorted(assignments) != [f"PILOT_R{i:02d}" for i in range(1, 6)]:
        raise SystemExit("assignment set is invalid")
    items: dict[str, str] = {}
    rows: list[dict[str, object]] = []
    for code in sorted(assignments):
        assigned = assignments[code]
        if not isinstance(assigned, list) or len(assigned) != 12:
            raise SystemExit(f"{code} must have 12 rows")
        for row in assigned:
            items.setdefault(str(row["pilot_item_id"]), str(row["sentence_text"]))
            rows.append(row)
    if len(items) != 12 or len(rows) != 60:
        raise SystemExit("R3 item or assignment count is invalid")
    item_sql = ",\n".join(
        f"  ({sql(declared)}, {sql(item_id)}, {sql(sentence)})"
        for item_id, sentence in sorted(items.items())
    )
    set_sql = ",\n".join(
        f"  ({sql(declared)}, {sql(code)}, 12)" for code in sorted(assignments)
    )
    assignment_sql = ",\n".join(
        "  (" + ", ".join([
            sql(declared), sql(str(row["pilot_rater_id"])), str(row["display_position"]),
            sql(str(row["pilot_item_id"])), sql(str(row["assignment_id"])),
        ]) + ")"
        for row in rows
    )
    migration = f"""-- Generated by tools/render_r3_transition.py from docs/instrument.json.
-- Append-only H2 -> H3 transition.  H2's excluded PI manual-test row is preserved.
begin;
set local standard_conforming_strings = on;

lock table research.pilot_instruments in share row exclusive mode;
lock table research.pilot_items in share row exclusive mode;
lock table research.pilot_assignment_sets in share row exclusive mode;
lock table research.pilot_assignments in share row exclusive mode;
lock table private.pilot_invites in share row exclusive mode;
lock table private.participant_identity in share row exclusive mode;
lock table research.pilot_submissions in share row exclusive mode;
lock table research.pilot_responses in share row exclusive mode;

do $r3_transition_guard$
begin
  if exists (select 1 from research.pilot_instruments where fielding_open) then
    raise exception 'H3 activation requires every fielding gate to be closed';
  end if;
  if (select count(*) from research.pilot_instruments where is_active) <> 1
     or not exists (select 1 from research.pilot_instruments where instrument_sha256 = {sql(H2_HASH)} and is_active) then
    raise exception 'H3 activation requires exactly active H2 baseline';
  end if;
  if exists (select 1 from private.pilot_invites where instrument_sha256 <> {sql(H2_HASH)})
     or exists (select 1 from research.pilot_submissions where instrument_sha256 <> {sql(H2_HASH)})
     or exists (select 1 from research.pilot_responses where instrument_sha256 <> {sql(H2_HASH)}) then
    raise exception 'unexpected non-H2 operational data exists';
  end if;
  if exists (
    select 1 from private.pilot_invites
    where instrument_sha256 = {sql(H2_HASH)}
      and (invite_purpose <> 'pi_manual_test' or used_at is null or submission_id is null)
  ) then
    raise exception 'H2 must contain only finalized PI manual-test history before H3 activation';
  end if;
  if exists (
    select 1 from research.pilot_submissions
    where instrument_sha256 = {sql(H2_HASH)}
      and (dataset_role <> 'synthetic_pi_manual_test' or not excluded_from_analysis
           or analysis_exclusion_reason <> 'pi_manual_test_never_analysis')
  ) then
    raise exception 'H2 historical submission is not permanently analysis-excluded';
  end if;
  if exists (select 1 from research.pilot_instruments where instrument_sha256 = {sql(declared)}) then
    raise exception 'H3 instrument already exists';
  end if;
end;
$r3_transition_guard$;

insert into research.pilot_instruments (
  instrument_sha256, instrument_version, source_offline_sha256,
  expected_response_count, is_active, fielding_open
) values (
  {sql(declared)}, {sql(str(instrument['hosted_version']))},
  {sql(str(instrument['source_offline_instrument_sha256']))},
  12, false, false
);

insert into research.pilot_items (instrument_sha256, pilot_item_id, sentence_text) values
{item_sql};

insert into research.pilot_assignment_sets (instrument_sha256, assignment_code, expected_item_count) values
{set_sql};

insert into research.pilot_assignments (
  instrument_sha256, assignment_code, display_position, pilot_item_id, assignment_id
) values
{assignment_sql};

do $r3_seed_validation$
begin
  if (select count(*) from research.pilot_items where instrument_sha256 = {sql(declared)}) <> 12
     or (select count(*) from research.pilot_assignment_sets where instrument_sha256 = {sql(declared)}) <> 5
     or (select count(*) from research.pilot_assignments where instrument_sha256 = {sql(declared)}) <> 60 then
    raise exception 'H3 seed counts are invalid';
  end if;
end;
$r3_seed_validation$;

update research.pilot_instruments
set is_active = false,
    fielding_open = false,
    fielding_closed_at = coalesce(fielding_closed_at, now())
where instrument_sha256 = {sql(H2_HASH)} and is_active;

update research.pilot_instruments
set is_active = true, activated_at = now(), fielding_open = false
where instrument_sha256 = {sql(declared)};

do $r3_activation_validation$
begin
  if (select count(*) from research.pilot_instruments where is_active) <> 1
     or not exists (select 1 from research.pilot_instruments where instrument_sha256 = {sql(declared)} and is_active and not fielding_open) then
    raise exception 'H3 did not become the sole active closed-gate instrument';
  end if;
end;
$r3_activation_validation$;

commit;
"""
    OUTPUT.write_text(migration, encoding="utf-8", newline="\n")
    print(f"Rendered {OUTPUT.name} instrument={declared}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
