-- Generated by tools/render_instrument_transition.py.
-- Previous source: supabase/instrument_history/v260903-pilot-hosted-1.instrument.json
-- Current source: docs/instrument.json
-- One-time append-only instrument transition; apply only after migration 004.
begin;
set transaction isolation level serializable;
set local standard_conforming_strings = on;

lock table
  research.pilot_instruments,
  research.pilot_items,
  research.pilot_assignment_sets,
  research.pilot_assignments,
  private.pilot_invites,
  private.participant_identity,
  research.pilot_submissions,
  research.pilot_responses
in access exclusive mode;

create temporary table _pilot_expected_invite_004_contract (
  token_hmac bytea not null,
  instrument_sha256 text not null,
  assignment_code text not null,
  revoked_at timestamptz,
  used_at timestamptz,
  invite_purpose text not null,
  admin_id_hmac bytea,
  constraint _pilot_expected_invite_purpose_ck check (
    invite_purpose in ('participant', 'disposable_e2e', 'pi_manual_test')
  ),
  constraint _pilot_expected_invite_admin_auth_ck check (
    (
      invite_purpose = 'pi_manual_test'
      and admin_id_hmac is not null
      and octet_length(admin_id_hmac) = 32
      and admin_id_hmac <> token_hmac
      and assignment_code = 'PILOT_R01'
    )
    or
    (
      invite_purpose in ('participant', 'disposable_e2e')
      and admin_id_hmac is null
    )
  )
) on commit drop;

create unique index _pilot_expected_admin_id_hmac_idx
  on _pilot_expected_invite_004_contract (admin_id_hmac)
  where admin_id_hmac is not null;

create unique index _pilot_expected_one_outstanding_pi_manual_test_idx
  on _pilot_expected_invite_004_contract (instrument_sha256)
  where invite_purpose = 'pi_manual_test'
    and revoked_at is null
    and used_at is null;

create temporary table _pilot_expected_submission_004_contract (
  dataset_role text not null,
  excluded_from_analysis boolean not null,
  analysis_exclusion_reason text not null,
  constraint _pilot_expected_submission_role_ck check (
    (
      dataset_role = 'synthetic_usability_pilot'
      and excluded_from_analysis
      and analysis_exclusion_reason = 'synthetic_usability_only_never_analysis'
    )
    or
    (
      dataset_role = 'synthetic_pi_manual_test'
      and excluded_from_analysis
      and analysis_exclusion_reason = 'pi_manual_test_never_analysis'
    )
  )
) on commit drop;

do $instrument_transition_precheck$
begin
  if to_regclass('private.pilot_withdrawal_events') is null then
    raise exception 'instrument transition requires the expected migration 003 schema';
  end if;
  if (
    select count(*)
    from pg_attribute
    where attrelid = 'private.pilot_invites'::regclass
      and attname in ('invite_purpose', 'admin_id_hmac')
      and attnum > 0
      and not attisdropped
  ) <> 2
     or not exists (
       select 1
       from pg_attribute
       where attrelid = 'private.pilot_invites'::regclass
         and attname = 'invite_purpose'
         and atttypid = 'text'::regtype
         and attnotnull
         and not atthasdef
         and attidentity = ''
         and attgenerated = ''
     )
     or not exists (
       select 1
       from pg_attribute
       where attrelid = 'private.pilot_invites'::regclass
         and attname = 'admin_id_hmac'
         and atttypid = 'bytea'::regtype
         and not attnotnull
         and not atthasdef
         and attidentity = ''
         and attgenerated = ''
     ) then
    raise exception 'instrument transition requires exact migration 004 columns';
  end if;
  if not exists (
       select 1
       from pg_constraint actual
       where actual.conrelid = 'private.pilot_invites'::regclass
         and actual.conname = 'pilot_invites_purpose_ck'
         and actual.contype = 'c'
         and actual.convalidated
         and not actual.connoinherit
         and pg_get_expr(actual.conbin, actual.conrelid, true) = (
           select pg_get_expr(expected.conbin, expected.conrelid, true)
           from pg_constraint expected
           where expected.conrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected.conname = '_pilot_expected_invite_purpose_ck'
         )
     )
     or not exists (
       select 1
       from pg_constraint actual
       where actual.conrelid = 'private.pilot_invites'::regclass
         and actual.conname = 'pilot_invites_admin_auth_ck'
         and actual.contype = 'c'
         and actual.convalidated
         and not actual.connoinherit
         and pg_get_expr(actual.conbin, actual.conrelid, true) = (
           select pg_get_expr(expected.conbin, expected.conrelid, true)
           from pg_constraint expected
           where expected.conrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected.conname = '_pilot_expected_invite_admin_auth_ck'
         )
     )
     or not exists (
       select 1
       from pg_constraint actual
       where actual.conrelid = 'research.pilot_submissions'::regclass
         and actual.conname = 'pilot_submissions_role_ck'
         and actual.contype = 'c'
         and actual.convalidated
         and not actual.connoinherit
         and pg_get_expr(actual.conbin, actual.conrelid, true) = (
           select pg_get_expr(expected.conbin, expected.conrelid, true)
           from pg_constraint expected
           where expected.conrelid =
             'pg_temp._pilot_expected_submission_004_contract'::regclass
             and expected.conname = '_pilot_expected_submission_role_ck'
         )
     ) then
    raise exception 'instrument transition requires exact migration 004 checks';
  end if;
  if not exists (
       select 1
       from pg_index actual
       join pg_class actual_index on actual_index.oid = actual.indexrelid
       where actual.indrelid = 'private.pilot_invites'::regclass
         and actual_index.relname = 'pilot_invites_admin_id_hmac_idx'
         and actual.indisunique
         and actual.indisvalid
         and actual.indisready
         and actual.indislive
         and not actual.indisprimary
         and not actual.indisexclusion
         and actual.indnkeyatts = 1
         and actual.indnatts = 1
         and pg_get_indexdef(actual.indexrelid, 1, true) = (
           select pg_get_indexdef(expected.indexrelid, 1, true)
           from pg_index expected
           join pg_class expected_index
             on expected_index.oid = expected.indexrelid
           where expected.indrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected_index.relname = '_pilot_expected_admin_id_hmac_idx'
         )
         and pg_get_expr(actual.indpred, actual.indrelid, true) = (
           select pg_get_expr(expected.indpred, expected.indrelid, true)
           from pg_index expected
           join pg_class expected_index
             on expected_index.oid = expected.indexrelid
           where expected.indrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected_index.relname = '_pilot_expected_admin_id_hmac_idx'
         )
     )
     or not exists (
       select 1
       from pg_index actual
       join pg_class actual_index on actual_index.oid = actual.indexrelid
       where actual.indrelid = 'private.pilot_invites'::regclass
         and actual_index.relname =
           'pilot_invites_one_outstanding_pi_manual_test_idx'
         and actual.indisunique
         and actual.indisvalid
         and actual.indisready
         and actual.indislive
         and not actual.indisprimary
         and not actual.indisexclusion
         and actual.indnkeyatts = 1
         and actual.indnatts = 1
         and pg_get_indexdef(actual.indexrelid, 1, true) = (
           select pg_get_indexdef(expected.indexrelid, 1, true)
           from pg_index expected
           join pg_class expected_index
             on expected_index.oid = expected.indexrelid
           where expected.indrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected_index.relname =
               '_pilot_expected_one_outstanding_pi_manual_test_idx'
         )
         and pg_get_expr(actual.indpred, actual.indrelid, true) = (
           select pg_get_expr(expected.indpred, expected.indrelid, true)
           from pg_index expected
           join pg_class expected_index
             on expected_index.oid = expected.indexrelid
           where expected.indrelid =
             'pg_temp._pilot_expected_invite_004_contract'::regclass
             and expected_index.relname =
               '_pilot_expected_one_outstanding_pi_manual_test_idx'
         )
     ) then
    raise exception 'instrument transition requires exact migration 004 indexes';
  end if;
  if (select count(*) from research.pilot_instruments) <> 1 then
    raise exception 'instrument transition requires exactly one baseline instrument';
  end if;
  if not exists (
    select 1
    from research.pilot_instruments
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
      and instrument_version = 'v260903-pilot-hosted-1'
      and source_offline_sha256 = 'b594a196eb7be720e57d974f4b5c6e4437b697e6ae20f01013e830af35707a51'
      and expected_response_count = 12
      and is_active is true
      and fielding_open is false
      and created_at is not null
      and activated_at = created_at
      and activated_at is not null
      and (
        (
          fielding_opened_at is null
          and fielding_closed_at is null
        )
        or
        (
          fielding_opened_at is not null
          and fielding_closed_at is not null
          and fielding_closed_at >= fielding_opened_at
        )
      )
  ) then
    raise exception 'instrument transition baseline state is invalid';
  end if;
  if exists (
    select 1 from research.pilot_instruments
    where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad'
       or instrument_version = 'v260903-pilot-hosted-2'
  ) then
    raise exception 'instrument transition target already exists';
  end if;
  if (select count(*) from research.pilot_items where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7') <> 12
     or (select count(*) from research.pilot_assignment_sets where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7') <> 5
     or (
       select count(*)
       from research.pilot_assignment_sets
       where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
         and assignment_code in ('PILOT_R01', 'PILOT_R02', 'PILOT_R03', 'PILOT_R04', 'PILOT_R05')
         and expected_item_count = 12
     ) <> 5
     or (select count(*) from research.pilot_assignments where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7') <> 60
     or exists (
       select 1
       from research.pilot_assignments
       where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
       group by assignment_code
       having count(*) <> 12
          or count(distinct display_position) <> 12
          or count(distinct pilot_item_id) <> 12
          or min(display_position) <> 1
          or max(display_position) <> 12
  ) then
    raise exception 'instrument transition baseline shape is invalid';
  end if;
  if exists (
    with expected_h1_items (
      pilot_item_id, sentence_text, created_with_instrument
    ) as (
      values
      ('USP_001', '그 위험이 커질 경우에는 앞에서 언급한 쪽으로 통화정책을 조정해야 한다.', true),
      ('USP_002', '고용 회복이 분명해질 때까지 현재의 완화적 통화 여건을 이어가는 편이 적절하다.', true),
      ('USP_003', '지속되는 가격 상승압력을 낮추기 위해 이번 회의에서 정책금리를 0.50%포인트 더 높이기로 결정한다.', true),
      ('USP_004', '생산 위축 우려와 가격 오름세 재확대 우려가 서로 상쇄되어 지금은 금리를 한 방향으로 움직일 근거가 없다.', true),
      ('USP_005', '단기자금시장의 경색을 풀기 위해 다음 주부터 금융기관에 공급하는 유동성 규모를 즉시 늘린다.', true),
      ('USP_006', '신용 팽창이 이어지는 만큼 다음 정책 변화의 무게중심은 긴축 쪽에 두어야 한다.', true),
      ('USP_007', '현재 자료는 금리를 올려야 할 이유와 내려야 할 이유를 비슷한 크기로 보여 준다.', true),
      ('USP_008', '과도한 시중 유동성을 회수하기 위해 다음 주부터 중앙은행의 정례 자금공급 규모를 즉시 축소한다.', true),
      ('USP_009', '수요의 급격한 위축을 막기 위해 이번 회의에서 정책금리를 0.50%포인트 더 낮추기로 결정한다.', true),
      ('USP_010', '경기 대응을 위해 금리 인상과 금리 인하를 모두 즉시 시행할 필요가 있다.', true),
      ('USP_011', '기조적 물가가 충분히 안정되기 전까지 제약적인 금융 여건을 그대로 유지하는 것이 바람직하다.', true),
      ('USP_012', '경기 하방위험이 더 커진다면 앞으로의 조정에서는 완화 가능성을 우선 검토해야 한다.', true)
    ),
    actual_h1_items (
      pilot_item_id, sentence_text, created_with_instrument
    ) as (
      select
        item.pilot_item_id,
        item.sentence_text,
        item.created_at = instrument.created_at
      from research.pilot_items item
      join research.pilot_instruments instrument
        on instrument.instrument_sha256 = item.instrument_sha256
      where item.instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
    ),
    actual_minus_expected as (
      select pilot_item_id, sentence_text, created_with_instrument
      from actual_h1_items
      except
      select pilot_item_id, sentence_text, created_with_instrument
      from expected_h1_items
    ),
    expected_minus_actual as (
      select pilot_item_id, sentence_text, created_with_instrument
      from expected_h1_items
      except
      select pilot_item_id, sentence_text, created_with_instrument
      from actual_h1_items
    )
    select 1 from actual_minus_expected
    union all
    select 1 from expected_minus_actual
  ) then
    raise exception 'instrument transition baseline item rows drifted';
  end if;
  if exists (
    with expected_h1_assignment_sets (
      assignment_code, expected_item_count, created_with_instrument
    ) as (
      values
      ('PILOT_R01', 12::smallint, true),
      ('PILOT_R02', 12::smallint, true),
      ('PILOT_R03', 12::smallint, true),
      ('PILOT_R04', 12::smallint, true),
      ('PILOT_R05', 12::smallint, true)
    ),
    actual_h1_assignment_sets (
      assignment_code, expected_item_count, created_with_instrument
    ) as (
      select
        assignment_set.assignment_code,
        assignment_set.expected_item_count,
        assignment_set.created_at = instrument.created_at
      from research.pilot_assignment_sets assignment_set
      join research.pilot_instruments instrument
        on instrument.instrument_sha256 = assignment_set.instrument_sha256
      where assignment_set.instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
    ),
    actual_minus_expected as (
      select assignment_code, expected_item_count, created_with_instrument
      from actual_h1_assignment_sets
      except
      select assignment_code, expected_item_count, created_with_instrument
      from expected_h1_assignment_sets
    ),
    expected_minus_actual as (
      select assignment_code, expected_item_count, created_with_instrument
      from expected_h1_assignment_sets
      except
      select assignment_code, expected_item_count, created_with_instrument
      from actual_h1_assignment_sets
    )
    select 1 from actual_minus_expected
    union all
    select 1 from expected_minus_actual
  ) then
    raise exception 'instrument transition baseline assignment-set rows drifted';
  end if;
  if exists (
    with expected_h1_assignments (
      assignment_code, display_position, pilot_item_id, assignment_id
    ) as (
      values
      ('PILOT_R01', 1::smallint, 'USP_011', 'USPILOT_R01_01'),
      ('PILOT_R01', 2::smallint, 'USP_010', 'USPILOT_R01_02'),
      ('PILOT_R01', 3::smallint, 'USP_008', 'USPILOT_R01_03'),
      ('PILOT_R01', 4::smallint, 'USP_003', 'USPILOT_R01_04'),
      ('PILOT_R01', 5::smallint, 'USP_004', 'USPILOT_R01_05'),
      ('PILOT_R01', 6::smallint, 'USP_006', 'USPILOT_R01_06'),
      ('PILOT_R01', 7::smallint, 'USP_005', 'USPILOT_R01_07'),
      ('PILOT_R01', 8::smallint, 'USP_009', 'USPILOT_R01_08'),
      ('PILOT_R01', 9::smallint, 'USP_012', 'USPILOT_R01_09'),
      ('PILOT_R01', 10::smallint, 'USP_007', 'USPILOT_R01_10'),
      ('PILOT_R01', 11::smallint, 'USP_002', 'USPILOT_R01_11'),
      ('PILOT_R01', 12::smallint, 'USP_001', 'USPILOT_R01_12'),
      ('PILOT_R02', 1::smallint, 'USP_007', 'USPILOT_R02_01'),
      ('PILOT_R02', 2::smallint, 'USP_009', 'USPILOT_R02_02'),
      ('PILOT_R02', 3::smallint, 'USP_002', 'USPILOT_R02_03'),
      ('PILOT_R02', 4::smallint, 'USP_006', 'USPILOT_R02_04'),
      ('PILOT_R02', 5::smallint, 'USP_012', 'USPILOT_R02_05'),
      ('PILOT_R02', 6::smallint, 'USP_001', 'USPILOT_R02_06'),
      ('PILOT_R02', 7::smallint, 'USP_010', 'USPILOT_R02_07'),
      ('PILOT_R02', 8::smallint, 'USP_004', 'USPILOT_R02_08'),
      ('PILOT_R02', 9::smallint, 'USP_005', 'USPILOT_R02_09'),
      ('PILOT_R02', 10::smallint, 'USP_011', 'USPILOT_R02_10'),
      ('PILOT_R02', 11::smallint, 'USP_008', 'USPILOT_R02_11'),
      ('PILOT_R02', 12::smallint, 'USP_003', 'USPILOT_R02_12'),
      ('PILOT_R03', 1::smallint, 'USP_007', 'USPILOT_R03_01'),
      ('PILOT_R03', 2::smallint, 'USP_005', 'USPILOT_R03_02'),
      ('PILOT_R03', 3::smallint, 'USP_009', 'USPILOT_R03_03'),
      ('PILOT_R03', 4::smallint, 'USP_008', 'USPILOT_R03_04'),
      ('PILOT_R03', 5::smallint, 'USP_002', 'USPILOT_R03_05'),
      ('PILOT_R03', 6::smallint, 'USP_012', 'USPILOT_R03_06'),
      ('PILOT_R03', 7::smallint, 'USP_011', 'USPILOT_R03_07'),
      ('PILOT_R03', 8::smallint, 'USP_003', 'USPILOT_R03_08'),
      ('PILOT_R03', 9::smallint, 'USP_001', 'USPILOT_R03_09'),
      ('PILOT_R03', 10::smallint, 'USP_006', 'USPILOT_R03_10'),
      ('PILOT_R03', 11::smallint, 'USP_004', 'USPILOT_R03_11'),
      ('PILOT_R03', 12::smallint, 'USP_010', 'USPILOT_R03_12'),
      ('PILOT_R04', 1::smallint, 'USP_010', 'USPILOT_R04_01'),
      ('PILOT_R04', 2::smallint, 'USP_001', 'USPILOT_R04_02'),
      ('PILOT_R04', 3::smallint, 'USP_012', 'USPILOT_R04_03'),
      ('PILOT_R04', 4::smallint, 'USP_006', 'USPILOT_R04_04'),
      ('PILOT_R04', 5::smallint, 'USP_004', 'USPILOT_R04_05'),
      ('PILOT_R04', 6::smallint, 'USP_005', 'USPILOT_R04_06'),
      ('PILOT_R04', 7::smallint, 'USP_011', 'USPILOT_R04_07'),
      ('PILOT_R04', 8::smallint, 'USP_007', 'USPILOT_R04_08'),
      ('PILOT_R04', 9::smallint, 'USP_003', 'USPILOT_R04_09'),
      ('PILOT_R04', 10::smallint, 'USP_002', 'USPILOT_R04_10'),
      ('PILOT_R04', 11::smallint, 'USP_008', 'USPILOT_R04_11'),
      ('PILOT_R04', 12::smallint, 'USP_009', 'USPILOT_R04_12'),
      ('PILOT_R05', 1::smallint, 'USP_007', 'USPILOT_R05_01'),
      ('PILOT_R05', 2::smallint, 'USP_002', 'USPILOT_R05_02'),
      ('PILOT_R05', 3::smallint, 'USP_011', 'USPILOT_R05_03'),
      ('PILOT_R05', 4::smallint, 'USP_012', 'USPILOT_R05_04'),
      ('PILOT_R05', 5::smallint, 'USP_010', 'USPILOT_R05_05'),
      ('PILOT_R05', 6::smallint, 'USP_003', 'USPILOT_R05_06'),
      ('PILOT_R05', 7::smallint, 'USP_001', 'USPILOT_R05_07'),
      ('PILOT_R05', 8::smallint, 'USP_004', 'USPILOT_R05_08'),
      ('PILOT_R05', 9::smallint, 'USP_005', 'USPILOT_R05_09'),
      ('PILOT_R05', 10::smallint, 'USP_006', 'USPILOT_R05_10'),
      ('PILOT_R05', 11::smallint, 'USP_009', 'USPILOT_R05_11'),
      ('PILOT_R05', 12::smallint, 'USP_008', 'USPILOT_R05_12')
    ),
    actual_h1_assignments (
      assignment_code, display_position, pilot_item_id, assignment_id
    ) as (
      select
        assignment_code,
        display_position,
        pilot_item_id,
        assignment_id
      from research.pilot_assignments
      where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
    ),
    actual_minus_expected as (
      select assignment_code, display_position, pilot_item_id, assignment_id
      from actual_h1_assignments
      except
      select assignment_code, display_position, pilot_item_id, assignment_id
      from expected_h1_assignments
    ),
    expected_minus_actual as (
      select assignment_code, display_position, pilot_item_id, assignment_id
      from expected_h1_assignments
      except
      select assignment_code, display_position, pilot_item_id, assignment_id
      from actual_h1_assignments
    )
    select 1 from actual_minus_expected
    union all
    select 1 from expected_minus_actual
  ) then
    raise exception 'instrument transition baseline assignment rows drifted';
  end if;
  if (select count(*) from private.pilot_invites) <> 0
     or (select count(*) from private.participant_identity) <> 0
     or (select count(*) from research.pilot_submissions) <> 0
     or (select count(*) from research.pilot_responses) <> 0 then
    raise exception 'instrument transition requires all mutable pilot tables to be empty';
  end if;
end;
$instrument_transition_precheck$;

insert into research.pilot_instruments (
  instrument_sha256,
  instrument_version,
  source_offline_sha256,
  expected_response_count,
  is_active,
  fielding_open
) values (
  '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad',
  'v260903-pilot-hosted-2',
  'b594a196eb7be720e57d974f4b5c6e4437b697e6ae20f01013e830af35707a51',
  12,
  false,
  false
);

insert into research.pilot_items (
  instrument_sha256, pilot_item_id, sentence_text
) values
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_001', '그 위험이 커질 경우에는 앞에서 언급한 쪽으로 통화정책을 조정해야 한다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_002', '고용 회복이 분명해질 때까지 현재의 완화적 통화 여건을 이어가는 편이 적절하다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_003', '지속되는 가격 상승압력을 낮추기 위해 이번 회의에서 정책금리를 0.50%포인트 더 높이기로 결정한다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_004', '생산 위축 우려와 가격 오름세 재확대 우려가 서로 상쇄되어 지금은 금리를 한 방향으로 움직일 근거가 없다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_005', '단기자금시장의 경색을 풀기 위해 다음 주부터 금융기관에 공급하는 유동성 규모를 즉시 늘린다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_006', '신용 팽창이 이어지는 만큼 다음 정책 변화의 무게중심은 긴축 쪽에 두어야 한다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_007', '현재 자료는 금리를 올려야 할 이유와 내려야 할 이유를 비슷한 크기로 보여 준다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_008', '과도한 시중 유동성을 회수하기 위해 다음 주부터 중앙은행의 정례 자금공급 규모를 즉시 축소한다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_009', '수요의 급격한 위축을 막기 위해 이번 회의에서 정책금리를 0.50%포인트 더 낮추기로 결정한다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_010', '경기 대응을 위해 금리 인상과 금리 인하를 모두 즉시 시행할 필요가 있다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_011', '기조적 물가가 충분히 안정되기 전까지 제약적인 금융 여건을 그대로 유지하는 것이 바람직하다.'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'USP_012', '경기 하방위험이 더 커진다면 앞으로의 조정에서는 완화 가능성을 우선 검토해야 한다.');

insert into research.pilot_assignment_sets (
  instrument_sha256, assignment_code, expected_item_count
) values
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 12),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 12),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 12),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 12),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 12);

insert into research.pilot_assignments (
  instrument_sha256, assignment_code, display_position, pilot_item_id, assignment_id
) values
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 1, 'USP_011', 'USPILOT_R01_01'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 2, 'USP_010', 'USPILOT_R01_02'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 3, 'USP_008', 'USPILOT_R01_03'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 4, 'USP_003', 'USPILOT_R01_04'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 5, 'USP_004', 'USPILOT_R01_05'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 6, 'USP_006', 'USPILOT_R01_06'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 7, 'USP_005', 'USPILOT_R01_07'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 8, 'USP_009', 'USPILOT_R01_08'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 9, 'USP_012', 'USPILOT_R01_09'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 10, 'USP_007', 'USPILOT_R01_10'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 11, 'USP_002', 'USPILOT_R01_11'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R01', 12, 'USP_001', 'USPILOT_R01_12'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 1, 'USP_007', 'USPILOT_R02_01'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 2, 'USP_009', 'USPILOT_R02_02'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 3, 'USP_002', 'USPILOT_R02_03'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 4, 'USP_006', 'USPILOT_R02_04'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 5, 'USP_012', 'USPILOT_R02_05'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 6, 'USP_001', 'USPILOT_R02_06'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 7, 'USP_010', 'USPILOT_R02_07'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 8, 'USP_004', 'USPILOT_R02_08'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 9, 'USP_005', 'USPILOT_R02_09'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 10, 'USP_011', 'USPILOT_R02_10'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 11, 'USP_008', 'USPILOT_R02_11'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R02', 12, 'USP_003', 'USPILOT_R02_12'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 1, 'USP_007', 'USPILOT_R03_01'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 2, 'USP_005', 'USPILOT_R03_02'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 3, 'USP_009', 'USPILOT_R03_03'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 4, 'USP_008', 'USPILOT_R03_04'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 5, 'USP_002', 'USPILOT_R03_05'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 6, 'USP_012', 'USPILOT_R03_06'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 7, 'USP_011', 'USPILOT_R03_07'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 8, 'USP_003', 'USPILOT_R03_08'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 9, 'USP_001', 'USPILOT_R03_09'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 10, 'USP_006', 'USPILOT_R03_10'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 11, 'USP_004', 'USPILOT_R03_11'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R03', 12, 'USP_010', 'USPILOT_R03_12'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 1, 'USP_010', 'USPILOT_R04_01'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 2, 'USP_001', 'USPILOT_R04_02'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 3, 'USP_012', 'USPILOT_R04_03'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 4, 'USP_006', 'USPILOT_R04_04'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 5, 'USP_004', 'USPILOT_R04_05'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 6, 'USP_005', 'USPILOT_R04_06'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 7, 'USP_011', 'USPILOT_R04_07'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 8, 'USP_007', 'USPILOT_R04_08'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 9, 'USP_003', 'USPILOT_R04_09'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 10, 'USP_002', 'USPILOT_R04_10'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 11, 'USP_008', 'USPILOT_R04_11'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R04', 12, 'USP_009', 'USPILOT_R04_12'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 1, 'USP_007', 'USPILOT_R05_01'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 2, 'USP_002', 'USPILOT_R05_02'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 3, 'USP_011', 'USPILOT_R05_03'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 4, 'USP_012', 'USPILOT_R05_04'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 5, 'USP_010', 'USPILOT_R05_05'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 6, 'USP_003', 'USPILOT_R05_06'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 7, 'USP_001', 'USPILOT_R05_07'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 8, 'USP_004', 'USPILOT_R05_08'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 9, 'USP_005', 'USPILOT_R05_09'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 10, 'USP_006', 'USPILOT_R05_10'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 11, 'USP_009', 'USPILOT_R05_11'),
  ('192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad', 'PILOT_R05', 12, 'USP_008', 'USPILOT_R05_12');

do $instrument_transition_seed_check$
begin
  if (select count(*) from research.pilot_items where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 12
     or (select count(*) from research.pilot_assignment_sets where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 5
     or (select count(*) from research.pilot_assignments where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 60
     or exists (
       select 1
       from research.pilot_assignments
       where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad'
       group by assignment_code
       having count(*) <> 12
          or count(distinct display_position) <> 12
          or count(distinct pilot_item_id) <> 12
          or min(display_position) <> 1
          or max(display_position) <> 12
     )
     or not exists (
       select 1 from research.pilot_instruments
       where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad'
         and instrument_version = 'v260903-pilot-hosted-2'
         and source_offline_sha256 = 'b594a196eb7be720e57d974f4b5c6e4437b697e6ae20f01013e830af35707a51'
         and expected_response_count = 12
         and is_active is false
         and fielding_open is false
         and activated_at is null
         and fielding_opened_at is null
         and fielding_closed_at is null
     ) then
    raise exception 'instrument transition target seed is invalid';
  end if;
end;
$instrument_transition_seed_check$;

do $instrument_transition_activation$
declare
  old_update_count integer;
  new_update_count integer;
begin
  update research.pilot_instruments
  set is_active = false
  where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
    and instrument_version = 'v260903-pilot-hosted-1'
    and is_active is true
    and fielding_open is false;
  get diagnostics old_update_count = row_count;
  if old_update_count <> 1 then
    raise exception 'instrument transition baseline activation update failed';
  end if;

  update research.pilot_instruments
  set is_active = true,
      activated_at = statement_timestamp()
  where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad'
    and instrument_version = 'v260903-pilot-hosted-2'
    and is_active is false
    and fielding_open is false
    and activated_at is null;
  get diagnostics new_update_count = row_count;
  if new_update_count <> 1 then
    raise exception 'instrument transition target activation update failed';
  end if;
end;
$instrument_transition_activation$;

do $instrument_transition_postcheck$
begin
  if (select count(*) from research.pilot_instruments) <> 2
     or (select count(*) from research.pilot_instruments where is_active is true) <> 1
     or not exists (
       select 1 from research.pilot_instruments
       where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
          and instrument_version = 'v260903-pilot-hosted-1'
          and is_active is false
          and fielding_open is false
          and activated_at is not null
          and (
            (
              fielding_opened_at is null
              and fielding_closed_at is null
            )
            or
            (
              fielding_opened_at is not null
              and fielding_closed_at is not null
              and fielding_closed_at >= fielding_opened_at
            )
          )
     )
     or not exists (
       select 1 from research.pilot_instruments
       where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad'
         and instrument_version = 'v260903-pilot-hosted-2'
         and is_active is true
         and fielding_open is false
         and activated_at is not null
         and fielding_opened_at is null
         and fielding_closed_at is null
     ) then
    raise exception 'instrument transition activation postcondition failed';
  end if;
  if (select count(*) from research.pilot_items where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 12
     or (select count(*) from research.pilot_assignment_sets where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 5
     or (select count(*) from research.pilot_assignments where instrument_sha256 = '192b618e620c653d5419eb602dcff5ca3f5346896b07bb5e24485fbd81e69dad') <> 60
     or (select count(*) from private.pilot_invites) <> 0
     or (select count(*) from private.participant_identity) <> 0
     or (select count(*) from research.pilot_submissions) <> 0
     or (select count(*) from research.pilot_responses) <> 0 then
    raise exception 'instrument transition row-count postcondition failed';
  end if;
end;
$instrument_transition_postcheck$;

commit;
