-- Generated by tools/render_instrument_seed.py from docs/instrument.json.
-- Immutable hosted pilot seed: no upsert, delete, identifier, invite, or secret data.
begin;
set local standard_conforming_strings = on;

insert into research.pilot_instruments (
  instrument_sha256,
  instrument_version,
  source_offline_sha256,
  expected_response_count,
  is_active,
  fielding_open,
  activated_at
) values (
  '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7',
  'v260903-pilot-hosted-1',
  'b594a196eb7be720e57d974f4b5c6e4437b697e6ae20f01013e830af35707a51',
  12,
  true,
  false,
  now()
);

insert into research.pilot_items (
  instrument_sha256, pilot_item_id, sentence_text
) values
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_001', '그 위험이 커질 경우에는 앞에서 언급한 쪽으로 통화정책을 조정해야 한다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_002', '고용 회복이 분명해질 때까지 현재의 완화적 통화 여건을 이어가는 편이 적절하다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_003', '지속되는 가격 상승압력을 낮추기 위해 이번 회의에서 정책금리를 0.50%포인트 더 높이기로 결정한다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_004', '생산 위축 우려와 가격 오름세 재확대 우려가 서로 상쇄되어 지금은 금리를 한 방향으로 움직일 근거가 없다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_005', '단기자금시장의 경색을 풀기 위해 다음 주부터 금융기관에 공급하는 유동성 규모를 즉시 늘린다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_006', '신용 팽창이 이어지는 만큼 다음 정책 변화의 무게중심은 긴축 쪽에 두어야 한다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_007', '현재 자료는 금리를 올려야 할 이유와 내려야 할 이유를 비슷한 크기로 보여 준다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_008', '과도한 시중 유동성을 회수하기 위해 다음 주부터 중앙은행의 정례 자금공급 규모를 즉시 축소한다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_009', '수요의 급격한 위축을 막기 위해 이번 회의에서 정책금리를 0.50%포인트 더 낮추기로 결정한다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_010', '경기 대응을 위해 금리 인상과 금리 인하를 모두 즉시 시행할 필요가 있다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_011', '기조적 물가가 충분히 안정되기 전까지 제약적인 금융 여건을 그대로 유지하는 것이 바람직하다.'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'USP_012', '경기 하방위험이 더 커진다면 앞으로의 조정에서는 완화 가능성을 우선 검토해야 한다.');

insert into research.pilot_assignment_sets (
  instrument_sha256, assignment_code, expected_item_count
) values
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 12),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 12),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 12),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 12),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 12);

insert into research.pilot_assignments (
  instrument_sha256, assignment_code, display_position, pilot_item_id, assignment_id
) values
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 1, 'USP_011', 'USPILOT_R01_01'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 2, 'USP_010', 'USPILOT_R01_02'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 3, 'USP_008', 'USPILOT_R01_03'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 4, 'USP_003', 'USPILOT_R01_04'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 5, 'USP_004', 'USPILOT_R01_05'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 6, 'USP_006', 'USPILOT_R01_06'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 7, 'USP_005', 'USPILOT_R01_07'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 8, 'USP_009', 'USPILOT_R01_08'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 9, 'USP_012', 'USPILOT_R01_09'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 10, 'USP_007', 'USPILOT_R01_10'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 11, 'USP_002', 'USPILOT_R01_11'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R01', 12, 'USP_001', 'USPILOT_R01_12'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 1, 'USP_007', 'USPILOT_R02_01'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 2, 'USP_009', 'USPILOT_R02_02'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 3, 'USP_002', 'USPILOT_R02_03'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 4, 'USP_006', 'USPILOT_R02_04'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 5, 'USP_012', 'USPILOT_R02_05'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 6, 'USP_001', 'USPILOT_R02_06'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 7, 'USP_010', 'USPILOT_R02_07'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 8, 'USP_004', 'USPILOT_R02_08'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 9, 'USP_005', 'USPILOT_R02_09'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 10, 'USP_011', 'USPILOT_R02_10'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 11, 'USP_008', 'USPILOT_R02_11'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R02', 12, 'USP_003', 'USPILOT_R02_12'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 1, 'USP_007', 'USPILOT_R03_01'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 2, 'USP_005', 'USPILOT_R03_02'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 3, 'USP_009', 'USPILOT_R03_03'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 4, 'USP_008', 'USPILOT_R03_04'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 5, 'USP_002', 'USPILOT_R03_05'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 6, 'USP_012', 'USPILOT_R03_06'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 7, 'USP_011', 'USPILOT_R03_07'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 8, 'USP_003', 'USPILOT_R03_08'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 9, 'USP_001', 'USPILOT_R03_09'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 10, 'USP_006', 'USPILOT_R03_10'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 11, 'USP_004', 'USPILOT_R03_11'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R03', 12, 'USP_010', 'USPILOT_R03_12'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 1, 'USP_010', 'USPILOT_R04_01'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 2, 'USP_001', 'USPILOT_R04_02'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 3, 'USP_012', 'USPILOT_R04_03'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 4, 'USP_006', 'USPILOT_R04_04'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 5, 'USP_004', 'USPILOT_R04_05'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 6, 'USP_005', 'USPILOT_R04_06'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 7, 'USP_011', 'USPILOT_R04_07'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 8, 'USP_007', 'USPILOT_R04_08'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 9, 'USP_003', 'USPILOT_R04_09'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 10, 'USP_002', 'USPILOT_R04_10'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 11, 'USP_008', 'USPILOT_R04_11'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R04', 12, 'USP_009', 'USPILOT_R04_12'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 1, 'USP_007', 'USPILOT_R05_01'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 2, 'USP_002', 'USPILOT_R05_02'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 3, 'USP_011', 'USPILOT_R05_03'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 4, 'USP_012', 'USPILOT_R05_04'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 5, 'USP_010', 'USPILOT_R05_05'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 6, 'USP_003', 'USPILOT_R05_06'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 7, 'USP_001', 'USPILOT_R05_07'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 8, 'USP_004', 'USPILOT_R05_08'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 9, 'USP_005', 'USPILOT_R05_09'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 10, 'USP_006', 'USPILOT_R05_10'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 11, 'USP_009', 'USPILOT_R05_11'),
  ('4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7', 'PILOT_R05', 12, 'USP_008', 'USPILOT_R05_12');

do $pilot_seed_validation$
declare
  invalid_assignment_count integer;
begin
  if (
    select count(*) from research.pilot_items
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
  ) <> 12 then
    raise exception 'pilot seed item count is not 12';
  end if;

  if (
    select count(*) from research.pilot_assignment_sets
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
  ) <> 5 then
    raise exception 'pilot seed assignment-set count is not 5';
  end if;

  if (
    select count(*) from research.pilot_assignments
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
  ) <> 60 then
    raise exception 'pilot seed assignment row count is not 60';
  end if;

  select count(*) into invalid_assignment_count
  from (
    select assignment_code
    from research.pilot_assignments
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
    group by assignment_code
    having count(*) <> 12
       or count(distinct display_position) <> 12
       or count(distinct pilot_item_id) <> 12
       or min(display_position) <> 1
       or max(display_position) <> 12
  ) as invalid_assignments;
  if invalid_assignment_count <> 0 then
    raise exception 'pilot seed contains an invalid 12-item assignment';
  end if;

  if exists (
    select 1 from research.pilot_instruments
    where instrument_sha256 = '4a07da2785bb2228787f2dd4e57339bd5c132111d693681a12cb62baf64978e7'
      and (instrument_version <> 'v260903-pilot-hosted-1'
        or source_offline_sha256 <> 'b594a196eb7be720e57d974f4b5c6e4437b697e6ae20f01013e830af35707a51'
        or expected_response_count <> 12
        or not is_active
        or fielding_open)
  ) then
    raise exception 'pilot seed instrument state is invalid';
  end if;
end;
$pilot_seed_validation$;

commit;
